{% set name = "pyearth" %}
{% set version = "0.1.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyearth-{{ version }}.tar.gz
  sha256: 7aabd8e689b1af5d64f247a7912679f208d1f1880d6ffe840ce61d3beb83ef84

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - cartopy
    - matplotlib-base
    - netcdf4
    - numpy
    - pandas
    - python >=3.8
    - scipy
    - statsmodels

test:
  imports:
    - pyearth
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/changliao1025/pyearth
  summary: Python for Earth Science.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - changliao1025
