context:
  name: pyearth
  version: 0.2.2

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/changliao1025/pyearth/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 4a21c13ed85223c95a836466a390150969b1c141abbba6262a115f09b40d0fb3

build:
  number: 0
  script: python -m pip install . -vv --no-build-isolation
  skip:
    - win and vc<14

requirements:
  build:
    - ${{ stdlib("c") }}
    - ${{ compiler('c') }}
  host:
    - pip
    - python
    - setuptools
    - numpy
    - cython >=0.29.0
  run:
    - python
    - ${{ pin_compatible('numpy') }}
    - gdal
    - netcdf4
    - pandas
    - scipy
    - rtree
    - geographiclib
    - statsmodels

tests:
  - python:
      imports:
        - pyearth
        - pyearth.gis.geometry.kernel
        - pyearth.gis.location.kernel
      pip_check: true

about:
  homepage: https://github.com/changliao1025/pyearth
  summary: Python for Earth Science.
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - changliao1025
  feedstock-name: ${{ name|lower }}
