{% set name = "pyearth" %}
{% set version = "0.1.20" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyearth-{{ version }}.tar.gz
  sha256: fe6bac6670292642cfce0ba5758a6e5424532d504a199baa6d4e58bf01ff8a92

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - cartopy
    - gdal
    - matplotlib-base
    - netcdf4
    - numpy
    - pandas
    - python >=3.8
    - scipy
    - statsmodels

test:
  imports:
    - pyearth
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/changliao1025/pyearth
  summary: Python for Earth Science.
  license: BSD-2-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - changliao1025
